import type { AppData } from "@/app/page"

export const mockApps: AppData[] = [
  {
    id: "1",
    name: "Visual Studio Code",
    developer: "Microsoft",
    icon: "/placeholder-dark.svg?height=80&width=80",
    description:
      "Visual Studio Code is a lightweight but powerful source code editor that runs on your desktop. It comes with built-in support for JavaScript, TypeScript and Node.js and has a rich ecosystem of extensions for other languages and runtimes.",
    shortDescription: "Powerful source code editor with built-in Git support",
    category: "Developer Tools",
    rating: 4.8,
    reviews: 125000,
    downloads: "50M+",
    size: "95 MB",
    version: "1.85.0",
    platforms: ["windows", "macos", "linux"],
    screenshots: [
      "/placeholder-dark.svg?height=400&width=800",
      "/placeholder-dark.svg?height=400&width=800",
      "/placeholder-dark.svg?height=400&width=800",
    ],
    price: "Free",
    installed: true,
    hasUpdate: true,
  },
  {
    id: "2",
    name: "Figma",
    developer: "Figma, Inc.",
    icon: "/placeholder-dark.svg?height=80&width=80",
    description:
      "Figma is a collaborative interface design tool that enables teams to design, prototype, and gather feedback all in one place.",
    shortDescription: "Collaborative design tool for teams",
    category: "Graphics & Design",
    rating: 4.9,
    reviews: 89000,
    downloads: "20M+",
    size: "120 MB",
    version: "124.0",
    platforms: ["windows", "macos", "linux"],
    screenshots: ["/placeholder-dark.svg?height=400&width=800", "/placeholder-dark.svg?height=400&width=800"],
    price: "Free",
    installed: true,
    hasUpdate: false,
  },
  {
    id: "3",
    name: "Slack",
    developer: "Salesforce",
    icon: "/placeholder-dark.svg?height=80&width=80",
    description:
      "Slack is a messaging app for business that connects people to the information they need. By bringing people together to work as one unified team, Slack transforms the way organizations communicate.",
    shortDescription: "Business messaging and collaboration platform",
    category: "Productivity",
    rating: 4.5,
    reviews: 200000,
    downloads: "100M+",
    size: "180 MB",
    version: "4.35.126",
    platforms: ["windows", "macos", "linux"],
    screenshots: ["/placeholder-dark.svg?height=400&width=800", "/placeholder-dark.svg?height=400&width=800"],
    price: "Free",
    installed: false,
    hasUpdate: false,
  },
  {
    id: "4",
    name: "Discord",
    developer: "Discord Inc.",
    icon: "/placeholder-dark.svg?height=80&width=80",
    description:
      "Discord is the easiest way to talk over voice, video, and text. Talk, chat, hang out, and stay close with your friends and communities.",
    shortDescription: "Voice, video, and text chat for communities",
    category: "Communication",
    rating: 4.6,
    reviews: 450000,
    downloads: "150M+",
    size: "160 MB",
    version: "0.0.292",
    platforms: ["windows", "macos", "linux"],
    screenshots: ["/placeholder-dark.svg?height=400&width=800", "/placeholder-dark.svg?height=400&width=800"],
    price: "Free",
    installed: true,
    hasUpdate: true,
  },
  {
    id: "5",
    name: "Notion",
    developer: "Notion Labs",
    icon: "/placeholder-dark.svg?height=80&width=80",
    description:
      "Notion is the all-in-one workspace for your notes, tasks, wikis, and databases. It's a new tool that blends your everyday work apps into one.",
    shortDescription: "All-in-one workspace for notes and collaboration",
    category: "Productivity",
    rating: 4.7,
    reviews: 95000,
    downloads: "30M+",
    size: "145 MB",
    version: "2.2.7",
    platforms: ["windows", "macos"],
    screenshots: ["/placeholder-dark.svg?height=400&width=800", "/placeholder-dark.svg?height=400&width=800"],
    price: "Free",
    installed: false,
    hasUpdate: false,
  },
  {
    id: "6",
    name: "Spotify",
    developer: "Spotify AB",
    icon: "/placeholder-dark.svg?height=80&width=80",
    description:
      "Spotify is a digital music streaming service that gives you access to millions of songs, podcasts, and videos from artists all over the world.",
    shortDescription: "Stream millions of songs and podcasts",
    category: "Music & Audio",
    rating: 4.4,
    reviews: 850000,
    downloads: "500M+",
    size: "130 MB",
    version: "1.2.25",
    platforms: ["windows", "macos", "linux"],
    screenshots: ["/placeholder-dark.svg?height=400&width=800", "/placeholder-dark.svg?height=400&width=800"],
    price: "Free",
    installed: true,
    hasUpdate: false,
  },
  {
    id: "7",
    name: "OBS Studio",
    developer: "OBS Project",
    icon: "/placeholder-dark.svg?height=80&width=80",
    description:
      "OBS Studio is free and open source software for video recording and live streaming. Stream to Twitch, YouTube and many other providers or record your own videos with high quality H264/AAC encoding.",
    shortDescription: "Free video recording and live streaming",
    category: "Video",
    rating: 4.8,
    reviews: 75000,
    downloads: "25M+",
    size: "210 MB",
    version: "30.0.2",
    platforms: ["windows", "macos", "linux"],
    screenshots: ["/placeholder-dark.svg?height=400&width=800", "/placeholder-dark.svg?height=400&width=800"],
    price: "Free",
    installed: false,
    hasUpdate: false,
  },
  {
    id: "8",
    name: "1Password",
    developer: "AgileBits",
    icon: "/placeholder-dark.svg?height=80&width=80",
    description:
      "1Password remembers all your passwords for you, and keeps them safe and secure behind the one password that only you know.",
    shortDescription: "Password manager and secure digital vault",
    category: "Security",
    rating: 4.9,
    reviews: 62000,
    downloads: "15M+",
    size: "85 MB",
    version: "8.10.18",
    platforms: ["windows", "macos", "linux"],
    screenshots: ["/placeholder-dark.svg?height=400&width=800", "/placeholder-dark.svg?height=400&width=800"],
    price: "$2.99/mo",
    installed: true,
    hasUpdate: true,
  },
  {
    id: "9",
    name: "Docker Desktop",
    developer: "Docker Inc.",
    icon: "/placeholder-dark.svg?height=80&width=80",
    description:
      "Docker Desktop is an easy-to-install application for your Mac or Windows environment that enables you to build and share containerized applications and microservices.",
    shortDescription: "Container development made easy",
    category: "Developer Tools",
    rating: 4.6,
    reviews: 45000,
    downloads: "10M+",
    size: "550 MB",
    version: "4.26.1",
    platforms: ["windows", "macos", "linux"],
    screenshots: ["/placeholder-dark.svg?height=400&width=800", "/placeholder-dark.svg?height=400&width=800"],
    price: "Free",
    installed: false,
    hasUpdate: false,
  },
  {
    id: "10",
    name: "Blender",
    developer: "Blender Foundation",
    icon: "/placeholder-dark.svg?height=80&width=80",
    description:
      "Blender is the free and open source 3D creation suite. It supports the entirety of the 3D pipeline—modeling, rigging, animation, simulation, rendering, compositing and motion tracking, video editing and 2D animation pipeline.",
    shortDescription: "Free 3D creation suite for everyone",
    category: "Graphics & Design",
    rating: 4.9,
    reviews: 120000,
    downloads: "40M+",
    size: "350 MB",
    version: "4.0.2",
    platforms: ["windows", "macos", "linux"],
    screenshots: ["/placeholder-dark.svg?height=400&width=800", "/placeholder-dark.svg?height=400&width=800"],
    price: "Free",
    installed: false,
    hasUpdate: false,
  },
  {
    id: "11",
    name: "Postman",
    developer: "Postman Inc.",
    icon: "/placeholder-dark.svg?height=80&width=80",
    description:
      "Postman is an API platform for building and using APIs. Postman simplifies each step of the API lifecycle and streamlines collaboration so you can create better APIs—faster.",
    shortDescription: "API development and testing platform",
    category: "Developer Tools",
    rating: 4.7,
    reviews: 58000,
    downloads: "18M+",
    size: "180 MB",
    version: "10.21.0",
    platforms: ["windows", "macos", "linux"],
    screenshots: ["/placeholder-dark.svg?height=400&width=800", "/placeholder-dark.svg?height=400&width=800"],
    price: "Free",
    installed: true,
    hasUpdate: false,
  },
  {
    id: "12",
    name: "VLC Media Player",
    developer: "VideoLAN",
    icon: "/placeholder-dark.svg?height=80&width=80",
    description:
      "VLC is a free and open source cross-platform multimedia player and framework that plays most multimedia files as well as DVDs, Audio CDs, VCDs, and various streaming protocols.",
    shortDescription: "Free multimedia player for all formats",
    category: "Video",
    rating: 4.8,
    reviews: 250000,
    downloads: "200M+",
    size: "45 MB",
    version: "3.0.20",
    platforms: ["windows", "macos", "linux"],
    screenshots: ["/placeholder-dark.svg?height=400&width=800", "/placeholder-dark.svg?height=400&width=800"],
    price: "Free",
    installed: false,
    hasUpdate: false,
  },
  {
    id: "13",
    name: "GIMP",
    developer: "GIMP Team",
    icon: "/placeholder-dark.svg?height=80&width=80",
    description:
      "GIMP is a cross-platform image editor available for GNU/Linux, macOS, Windows and more. It is free software, you can change its source code and distribute your changes.",
    shortDescription: "Free & open source image editor",
    category: "Graphics & Design",
    rating: 4.5,
    reviews: 85000,
    downloads: "35M+",
    size: "280 MB",
    version: "2.10.36",
    platforms: ["windows", "macos", "linux"],
    screenshots: ["/placeholder-dark.svg?height=400&width=800", "/placeholder-dark.svg?height=400&width=800"],
    price: "Free",
    installed: false,
    hasUpdate: false,
  },
  {
    id: "14",
    name: "Audacity",
    developer: "Audacity Team",
    icon: "/placeholder-dark.svg?height=80&width=80",
    description:
      "Audacity is an easy-to-use, multi-track audio editor and recorder for Windows, macOS, GNU/Linux and other operating systems.",
    shortDescription: "Free multi-track audio editor",
    category: "Music & Audio",
    rating: 4.6,
    reviews: 95000,
    downloads: "45M+",
    size: "90 MB",
    version: "3.4.2",
    platforms: ["windows", "macos", "linux"],
    screenshots: ["/placeholder-dark.svg?height=400&width=800", "/placeholder-dark.svg?height=400&width=800"],
    price: "Free",
    installed: false,
    hasUpdate: false,
  },
  {
    id: "15",
    name: "Bitwarden",
    developer: "Bitwarden Inc.",
    icon: "/placeholder-dark.svg?height=80&width=80",
    description:
      "Bitwarden is a free and open-source password management service that stores sensitive information such as website credentials in an encrypted vault.",
    shortDescription: "Open source password manager",
    category: "Security",
    rating: 4.8,
    reviews: 48000,
    downloads: "8M+",
    size: "75 MB",
    version: "2024.1.0",
    platforms: ["windows", "macos", "linux"],
    screenshots: ["/placeholder-dark.svg?height=400&width=800", "/placeholder-dark.svg?height=400&width=800"],
    price: "Free",
    installed: false,
    hasUpdate: false,
  },
]
